{{- if .Values.api.automaticallyMigrate -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cocov-chart.fullname" . }}-api-migrations
  labels:
    {{- include "cocov-chart.labels" . | nindent 4 }}
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 1200
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: api-migrations
        {{- with (mergeOverwrite .Values.general.podAnnotations .Values.api.podAnnotations) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        dev.cocov.k8s/component: api-migrations
        {{- $defaultSelectors := (include "cocov-chart.selectorLabels" .) | fromYaml }}
        {{- range $key, $value := mergeOverwrite $defaultSelectors .Values.api.labels .Values.general.labels }}
        {{ $key }}: {{ toYaml $value }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "cocov-chart.serviceAccountName" . }}
      securityContext:
        {{- range $key, $value := mergeOverwrite .Values.general.podSecurityContext .Values.api.podSecurityContext }}
        {{ $key }}: {{ toYaml $value }}
        {{- end }}
      containers:
        - name: api-migrations
          env:
          {{- include "apiEnvs" . | nindent 10 }}
          securityContext:
            {{- range $key, $value := mergeOverwrite .Values.general.securityContext .Values.api.securityContext }}
            {{ $key }}: {{ toYaml $value }}
            {{- end }}
          image: {{ include "dockerHubImage" (list "api" (.Values.api.version | default .Values.defaultVersions.api )) }}
          imagePullPolicy: {{ .Values.general.imagePullPolicy | default "IfNotPresent" }}
          command: ["bundle"]
          args: ["exec", "rails", "db:migrate"]
          resources:
          {{- toYaml .Values.api.resources | nindent 12 }}
      restartPolicy: OnFailure
      {{- with mergeOverwrite .Values.general.nodeSelector .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with mergeOverwrite .Values.general.affinity .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with concat .Values.general.tolerations .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
