{{- if and .Values.badger.enabled .Values.badger.ingress.enabled -}}
{{- $fullName := include "cocov-chart.fullname" . -}}
{{- if and .Values.badger.ingress.ingressClassName (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.badger.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.badger.ingress.annotations "kubernetes.io/ingress.class" .Values.badger.ingress.ingressClassName }}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-badger-ingress
  labels:
    {{- include "cocov-chart.labels" . | nindent 4 }}
  {{- with .Values.badger.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.badger.ingress.ingressClassName (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.badger.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.badger.ingress.tls }}
  tls:
    {{ .Values.badger.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.badger.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-badger
                port:
                  name: http
              {{- else }}
              serviceName: {{ $fullName }}-badger
              servicePort: http
              {{- end }}
    {{- end }}
{{- end }}
