apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cocov-chart.fullname" . }}-sidekiq
  labels:
    {{- include "cocov-chart.labels" . | nindent 4 }}
spec:
  {{- if .Values.general.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.general.revisionHistoryLimit }}
  {{- end }}
  {{- if not .Values.sidekiq.hpa.enabled }}
  replicas: {{ .Values.sidekiq.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cocov-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: sidekiq
        {{- with (mergeOverwrite .Values.general.podAnnotations .Values.sidekiq.podAnnotations) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        dev.cocov.k8s/component: sidekiq
        {{- $defaultSelectors := (include "cocov-chart.selectorLabels" .) | fromYaml }}
        {{- range $key, $value := mergeOverwrite $defaultSelectors .Values.sidekiq.labels .Values.general.labels }}
        {{ $key }}: {{ toYaml $value }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "cocov-chart.serviceAccountName" . }}
      securityContext:
        {{- range $key, $value := mergeOverwrite .Values.general.podSecurityContext .Values.sidekiq.podSecurityContext }}
        {{ $key }}: {{ toYaml $value }}
        {{- end }}
      containers:
        - name: sidekiq
          command:
            - bundle
            - exec
            - sidekiq
          env:
          {{- include "apiEnvs" . | nindent 12 }}
          securityContext:
            {{- range $key, $value := mergeOverwrite .Values.general.securityContext .Values.sidekiq.securityContext }}
            {{ $key }}: {{ toYaml $value }}
            {{- end }}
          image: {{ include "dockerHubImage" (list "api" (.Values.api.version | default .Values.defaultVersions.api )) }}
          imagePullPolicy: {{ .Values.general.imagePullPolicy | default "IfNotPresent" }}
          {{- if .Values.storage.local.volume }}
          volumeMounts:
            - mountPath: {{ .Values.storage.local.mountPath }}
              name: cocov-git-storage-volume
          {{- end }}
          {{/* TODO @vito: Liveness probe to Sidekiq (COC-70)
          livenessProbe:
            httpGet:
              path: /v1/ping
              port: http
          readinessProbe:
            httpGet:
              path: /v1/ping
              port: http
           */}}
          resources:
            {{- toYaml .Values.sidekiq.resources | nindent 12 }}
      {{- if .Values.storage.local.volume }}
      volumes:
        {{- list (mergeOverwrite .Values.storage.local.volume ("{ name: cocov-git-storage-volume }" | fromYaml)) | toYaml | nindent 8 }}
      {{- end }}
      {{- with mergeOverwrite .Values.general.nodeSelector .Values.sidekiq.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with mergeOverwrite .Values.general.affinity .Values.sidekiq.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with concat .Values.general.tolerations .Values.sidekiq.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
