{{- if .Values.badger.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cocov-chart.fullname" . }}-badger
  labels:
    {{- include "cocov-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    dev.cocov.k8s/component: badger
    {{- include "cocov-chart.selectorLabels" . | nindent 4 }}
{{- end -}}
